# Generated by Django 4.1.3 on 2022-11-28 09:56

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('title', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=101000, size=1000)),
                ('play_list', django_mysql.models.ListCharField(models.CharField(max_length=10000), max_length=20002, size=2)),
                ('volume', models.IntegerField(default=50)),
            ],
        ),
    ]
